### ISSUE TITLE
php5.6环境下登陆报错

### ISSUE THREAD

**Issue by 120318** [laynefyc/php-monitor#10]
```
/?r=login/account - Default value for parameters with a class type hint can only be NULL in /tmp/php-monitor/vendor/phpunit/phpunit/src/Framework/Assert/Functions.php on line 79
```

![image](https://user-images.githubusercontent.com/20685540/86043301-15efc400-ba7b-11ea-840d-78b091446398.png)

**Comment by 120318** [comment]
能否提供一份php5.6版本的composer.json

**Comment by laynefyc** [comment]
"illuminate/database": "~5.8",
        "jenssegers/mongodb": "^3.5",
        "illuminate/pagination": "^5.8"  

只依赖这三个composer包，三个包都有对应的文档和php版本，改下版本号即可。

**Comment by 120318** [comment]
嗯，修改后确实可以成功呢，但实际上的情况是，在php5.6环境下，三种存储都存在问题，而且都无法使用，感觉是没有在php5.6版本测试过。

**Comment by laynefyc** [comment]
@dearjoey  贴一下报错信息吧，php5.6三种存储方式都是测试过的。

**Comment by 120318** [comment]
抱歉，没有现场了，已经改用xhgui了:>
