### ISSUE TITLE
目前使用过程中发现了几个问题

### ISSUE THREAD

**Issue by DanielZhao1990** [laynefyc/php-monitor#14]
首先感谢作者的项目，以下我是在使用过程中发现的几个问题。
使用环境
- php版本7.2.33 
- xhprof版本2.2.3

1. profiler enable 设置无效.
`$config['profiler']['enable']`改为`$config['profiler']['enable']()`后修复
2. 显示内存占用会出现负值情况
![image](https://user-images.githubusercontent.com/4916621/103985292-a4c86080-51c3-11eb-8ceb-daab74d45277.png)
3. SQL耗时永远都是0μs

**Comment by laynefyc** [comment]
PHP 5.6(download tideways v4.1.5) PHP 7.0+(download tideways v4.1.7) 。xhprof 扩展太老了，对PHP7+兼容性比较差。
